# --- Docker Compose File for Development ---
# services: Defines the different containers that make up your application.
services:
  app:
    # container_name: This is the equivalent of the '--name' flag in your docker run command.
    container_name: trello-card-scheduler

    # build: Tells Docker Compose how to build the image for this service.
    build:
      # context: The path to the directory containing the Dockerfile. '.' means the current directory.
      context: .
      # dockerfile: The name of the Dockerfile to use.
      dockerfile: Dockerfile.dev

    # ports: This is the equivalent of the '-p' flag. It maps host ports to container ports.
    ports:
      - "3000:3000" # For the React frontend
      - "5000:5000" # For the Node.js backend

    # volumes: This is the key section for enabling live code changes.
    volumes:
      # Syncs the entire project directory on your machine to the /app directory in the container.
      - .:/app
      # These "anonymous volumes" prevent local node_modules from overwriting the container's.
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules

    # environment: This sets the environment variables inside the container.
    environment:
      - DB_HOST=192.168.1.121
      - DB_USER=trelloSchedulerAdmin
      - DB_PASSWORD=odE1M9d*oWXZj@Uh4Ooa
      - DB_NAME=trelloSchedulerDev
      - DB_PORT=5432
      - TZ=America/New_York
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true