# .github/workflows/ci.yml

name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  # Job to build and test the React frontend
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    # Specify the directory where the frontend code lives
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Run Frontend Tests
        run: npm test

  # Job to install and test the Node.js backend
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    # Specify the directory where the backend code lives
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install Backend Dependencies
        run: npm ci

      # We will add a test script to the backend in the next step
      - name: Run Backend Tests
        run: npm test
